exclude: ^flipper_thrift|flipper_client\.egg_info|build$
repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.620
    hooks:
        - id: mypy
          args:
            - --follow-imports=silent
            - --ignore-missing-imports
  - repo: https://github.com/ambv/black
    rev: master
    hooks:
      - id: black
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.1.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: flake8
