version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pipenv install -e .[dev]
      - run: pipenv run pytest tests
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
