name: Snyk vulnerability check - python-3.8

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  snyk-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Installing snyk-delta
        run: npm i -g snyk-delta

      - name: Use python3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: "pip install --index-url=https://dl.cloudsmith.io/${{secrets.CLOUDSMITH_PIP}}/carta/pip/python/index/ --extra-index-url=https://dl.cloudsmith.io/${{secrets.CLOUDSMITH_PIP_TEST}}/carta/pip-test/python/index/ --editable ./build/python/"
        env:
          CLOUDSMITH_PIP: ${{ secrets.CLOUDSMITH_PIP }}
          CLOUDSMITH_PIP_TEST: ${{ secrets.CLOUDSMITH_PIP_TEST }}
      - uses: snyk/actions/setup@master
      - name: Snyk Test
        run: snyk test --json --file=./build/python/setup.py --skip-unresolved=false --print-deps --severity-threshold=high --org='c3b4154f-555f-4c13-9284-de06d25b4c03' | snyk-delta --baselineOrg 'c3b4154f-555f-4c13-9284-de06d25b4c03' --baselineProject ''
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
